spring:
  freemarker:
    cache: false
    settings:
      output_encoding: UTF-8
  datasource:
    url: jdbc:h2:file:./data/drink;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;COLLATION=CZECH
    driverClassName: org.h2.Driver
    username: sa
    password: ''